#!/bin/bash -e

set -x

SBT_HOME=/tmp/sbt

if ! [ -d $SBT_HOME ]; then
  mkdir -p $SBT_HOME/bin
  curl -L https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.12/sbt-launch.jar -o $SBT_HOME/bin/sbt-launch.jar

  cat << "EOF" > $SBT_HOME/bin/sbt
#!/bin/bash

SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
java $SBT_OPTS -jar `dirname $0`/sbt-launch.jar "$@"

EOF

chmod u+x $SBT_HOME/bin/sbt
export PATH=$SBT_HOME/bin:$PATH
